# Generated by Django 2.2.2 on 2019-06-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('problem', models.CharField(choices=[('Web', 'Web'), ('Android App', 'Android App'), ('IOS App', 'IOS App')], max_length=20)),
                ('complaint', models.TextField()),
            ],
        ),
    ]
